### ISSUE TITLE
Cannot install groups addon

### ISSUE THREAD

**Issue by vogtmh** [serjoscha87/cockpit_GROUPS#12]
I cannot install / use the addon. Readme says to create a subfolder "addons" in the Cockpit root (/usr/share/cockpit on Ubuntu 18.04) and copy the Groups folder into it. But I cannot see it anywhere in the interface.

Cockpit version is 215.

**Comment by serjoscha87** [comment]
I just tested it with the latest version - it still works

https://imgur.com/uVWl2oT
