### ISSUE TITLE
Error while trying to save a new group

### ISSUE THREAD

**Issue by dragosdydy** [serjoscha87/cockpit_GROUPS#13]
I have recently just installed the addon to a fairly new Cockpit instance that's using MongoDB and I cannot save a group. I'm using the addon successfully in a different instance (older version of Cockpit and Addon).

Steps to reproduce:
- Install the plugin;
- Go to Groups page;
- Configure the group with the needed details;
- Press "Save";
- Notice that nothing happens.

Looking into the console, there is a 500 Error on `/groups/save` with the following details:

> error: "invalid document for insert: keys cannot contain ".": "finder.path""
> file: "/var/www/html/lib/vendor/mongodb/mongodb/src/Operation/InsertOne.php"
> line: 112

Cockpit version: 0.10.0

Does anyone have any suggestions about this? Thanks in advance.

**Comment by sainf** [comment]
MongoDB libs comp prob, fix with this patch: https://github.com/serjoscha87/cockpit_GROUPS/compare/mongodb-patch?diff=unified

**Comment by bassauer-storms-media** [comment]
So this problem seems to be related to the DB you are using to run cockpit, right? 

If so I guess this is not an Plugin issue. Besides I do not support other DB platforms then SQL-Lite for this addon

**Comment by dragosdydy** [comment]
@sainf thank you for the link, looks like everything is working by using that mongodb patch. I was not aware of it! 
@bassauer-storms-media indeed, I was not aware it's not working on mogodb. Thank you.
