### ISSUE TITLE
Problem with Groups UI

### ISSUE THREAD

**Issue by wiedaw** [serjoscha87/cockpit_GROUPS#14]
Hello. I've put Groups folder into /cockpit/addons directory as is said in Installation paragraph but nothing has changed. 
I can't see box "Group" in Setting. Should I change something in code?

**Comment by bassauer-storms-media** [comment]
No you don't have to change the code - the addon works out of the box.

You should see it in the cockpit system menu (when you click on the cockpit icon in the very left corner next to the label "Cockpit")

**Comment by wiedaw** [comment]
Thank you, finally everything is ok.
