### ISSUE TITLE
What license applies to the plugin source code?

### ISSUE THREAD

**Issue by ghost** [serjoscha87/cockpit_GROUPS#18]
Hi,

Thanks for creating this awesome plugin, it is very useful for me and my co-workers. In my company we will use Cockpit CMS, and we would like to use this plugin also. I have a question about licence therefore, because I can not find it in repository. 

Can we use this plugin with the same licence as the main project? Cockpit CMS is distributed on MIT licence.

Thanks from advance for reply and have a nice day! :)

**Comment by serjoscha87** [comment]
You can do what ever you want with that code - its completely free for everything you are waning to do with it. Spread it, change it, or do what ever you would like to do with it

:)
