### ISSUE TITLE
Visibility per collection

### ISSUE THREAD

**Issue by yusufiga** [serjoscha87/cockpit_GROUPS#3]
Hi,

Thank you for this great addon. I'm wondering if it's possible to limit visibility of some collections. i.e lets say I want "statistics collection" to be visible to managers but hidden for content providers.

If you think this will make your addon too complicated or it's not a wanted feature for your addon you can just close the issue.

Thanks,
Yusuf

**Comment by yusufiga** [comment]
Thanks for the explanation with screenshots 👍  I will just close this issue :)

**Comment by serjoscha87** [comment]
so I got you right and this solves your problem?

If yes: glad to help, have a nice day! :)

**Comment by yusufiga** [comment]
Yes it does thanks again :)
