### ISSUE TITLE
wrong path for assets if cockpit is in subfolder

### ISSUE THREAD

**Issue by raffaelj** [serjoscha87/cockpit_GROUPS#4]
When I load my cockpit from localhost/cockpit, groups.css and groups.js have wrong paths (localhost/addons/Groups...).

`$app->path('groups', 'addons/Groups/');`

I found three ways to solve it, but I tested it only on localhost.

```php
$app->path('groups', '/addons/Groups/'); // with slash before addons
$app->path('groups', $app['base_route'].'addons/Groups/'); // adds 'cockpit/'
$app->path('groups', __DIR__); // current path
```

I prefer the one with `__DIR__`. This way the addon still works if I don't rename it from 'cockpit_GROUPS' to 'Groups'.

I didn't test this, but it's possible to define a custom module dir in config (loadmodules: dirnames). The version with `__DIR__` should work there, too.

**Comment by serjoscha87** [comment]
thank you - gonna change that (and I also gonna put the files back into a sub dir called "Groups" again)
