### ISSUE TITLE
In attempting to save permissions for collections with groups, I get a "saving failed"

### ISSUE THREAD

**Issue by jasonday** [serjoscha87/cockpit_GROUPS#9]
as title reads, when I adjust permissions settings in a collection for a group I've created with this addon, the changes will not save and a returned error of "saving failed"

**Comment by serjoscha87** [comment]
well - this must be due an cockpit update.. this addon just used to work. unfortunately im am very short on time and I won't be able to check that problem that soon. Sorry

**Comment by jasonday** [comment]
Turns out it was due to a cloned collection (using phpmyadmin). For some reason, the addon and other permissions would not work. Exported/deleted/imported collection and all was fine.
